### ISSUE TITLE
Questions about the cam method.

### ISSUE THREAD

**Issue by icoderzqliu** [Zefan-Cai/KVCache-Factory#35]
请问仓库中实现的cam算法的原理是否和原文章有出入？

[原文章](https://openreview.net/pdf?id=LCTmppB165) 是把即将丢弃的token合并到后续的token中，但是在仓库中cam的代码实现中，在选完topk重要的token并丢弃之后才做了[merge](https://github.com/Zefan-Cai/KVCache-Factory/blob/a3ee1fcda483c633e4273b2bed3fd508b9cbc467/pyramidkv/pyramidkv_utils.py#L241)操作，而且是在已经留下出来那些token中，将一个token的信息[加到后续的token中](https://github.com/Zefan-Cai/KVCache-Factory/blob/a3ee1fcda483c633e4273b2bed3fd508b9cbc467/pyramidkv/pyramidkv_utils.py#L255)，想请问一下这样的实现是否合理，不会出现信息冲突的问题吗？

或许也是我哪里理解出了问题，期待您对这部分代码做出解释，谢谢！

**Comment by Linking-ai** [comment]
您好，感谢您及时指出问题。目前我们正在完善merge部分的实现。

关于仓库中CAM代码的实现，确实如您所说，它是在已经选择出的TopK tokens中，将前面一些token的信息加到后续token中，这与原始CAM方法在实现上存在一定差异。

我们在这部分merge操作的实现上，遵循了CAM方法的原始思路，即将前面一些token的信息加到后续token中，实质上是对value_states信息进行了聚合。为了便于与我们的方法进行对比并统一管理budget，我们仍然保留TopK tokens作为budget。然而，这里实现的顺序确实存在问题，应该是先采用CAM的merge方法聚合token信息后，再通过TopK保留相同budget的tokens。

我将尽快提交新的PR来修复这个问题。

再次感谢您及时反馈并指出我们的实现问题。我们会继续改进merge操作，并确保其更加符合CAM方法的原意。

**Comment by icoderzqliu** [comment]
> 您好，感谢您及时指出问题。目前我们正在完善merge部分的实现。
> 
> 关于仓库中CAM代码的实现，确实如您所说，它是在已经选择出的TopK tokens中，将前面一些token的信息加到后续token中，这与原始CAM方法在实现上存在一定差异。
> 
> 我们在这部分merge操作的实现上，遵循了CAM方法的原始思路，即将前面一些token的信息加到后续token中，实质上是对value_states信息进行了聚合。为了便于与我们的方法进行对比并统一管理budget，我们仍然保留TopK tokens作为budget。然而，这里实现的顺序确实存在问题，应该是先采用CAM的merge方法聚合token信息后，再通过TopK保留相同budget的tokens。
> 
> 我将尽快提交新的PR来修复这个问题。
> 
> 再次感谢您及时反馈并指出我们的实现问题。我们会继续改进merge操作，并确保其更加符合CAM方法的原意。

感谢您的细致回复。

想再问一下关于代码细节的问题：
1. 对于`start_budget`的设计考虑
2. `merge_prob`是根据`attn_score`中（全局的seq_len）第`token_index - recent_budget`位置的得分算出来的，而用于merge的token是根据已经压缩过的`value_states`中第`token_index - recent_budget`位置来merge的，这两个位置对应的token应该都不是同一个，这里对于这部分代码实现还是有点困惑，希望能够对这部分代码进行详细解释，谢谢！

**Comment by Linking-ai** [comment]
> > 您好，感谢您及时指出问题。目前我们正在完善merge部分的实现。
> > 关于仓库中CAM代码的实现，确实如您所说，它是在已经选择出的TopK tokens中，将前面一些token的信息加到后续token中，这与原始CAM方法在实现上存在一定差异。
> > 我们在这部分merge操作的实现上，遵循了CAM方法的原始思路，即将前面一些token的信息加到后续token中，实质上是对value_states信息进行了聚合。为了便于与我们的方法进行对比并统一管理budget，我们仍然保留TopK tokens作为budget。然而，这里实现的顺序确实存在问题，应该是先采用CAM的merge方法聚合token信息后，再通过TopK保留相同budget的tokens。
> > 我将尽快提交新的PR来修复这个问题。
> > 再次感谢您及时反馈并指出我们的实现问题。我们会继续改进merge操作，并确保其更加符合CAM方法的原意。
> 
> 感谢您的细致回复。
> 
> 想再问一下关于代码细节的问题：
> 
> 1. 对于`start_budget`的设计考虑
> 2. `merge_prob`是根据`attn_score`中（全局的seq_len）第`token_index - recent_budget`位置的得分算出来的，而用于merge的token是根据已经压缩过的`value_states`中第`token_index - recent_budget`位置来merge的，这两个位置对应的token应该都不是同一个，这里对于这部分代码实现还是有点困惑，希望能够对这部分代码进行详细解释，谢谢！

感谢您的回复。

1. 关于`start_budget`的设计，我们基本遵循了CAM原始的实现，并且默认比例为0.1。后续可能会根据保留的TopK tokens的数量、indices，以及相应的recent tokens（window_size）来进行调整。

2. 这部分代码是根据（[CAM](https://github.com/zyxxmu/cam/blob/fc80e64f460b343be96c87596f2494fc9d319c45/cam_hf/utils_lm_eval/modify_llama_cam.py#L29)）实现的。我的理解是，在merge操作中，`merge_prob`是基于当前token与前面若干token的注意力关系来计算的。`merge_prob`使用的是`attn_score[0, :, token_index - recent_budget]`，即基于未压缩的token，因为注意力矩阵是基于全局的`seq_len`计算的。然而，用于实际合并的`value_states`是基于已压缩的token。每次合并时，当前token被映射到经过压缩后的`value_states`中的位置。这个设计的核心想法是，通过全局的注意力分布来确定哪些token可以合并，虽然操作发生在已压缩的token上，但合并概率却是基于原始（未压缩的）attention scores计算的，即仍然基于全局的`seq_len`。

这部分实现确实可能存在问题，我在实现时也遇到了一些困惑。后续我们会进一步完善，欢迎您与我交流，您可以通过微信zhenglin_wang01联系我。
