### ISSUE TITLE
Cache Budget

### ISSUE THREAD

**Issue by Couteaux123** [Zefan-Cai/KVCache-Factory#36]
May I ask why the calculation of the number of kv caches in each layer of your code is not divided by m, but written in the article?
![image](https://github.com/user-attachments/assets/657eeeda-073c-4e26-ac68-95dd028341a4)

**Comment by Zefan-Cai** [comment]
Actually it should be divided by m. In this case m equals to num_hidden_layers - 1. You can treat num_hidden_layers - 1 as m and put steps into the equation of the last line.

Thanls for pointing out. I hope this could make it easy to understand.

**Comment by Couteaux123** [comment]
Thanks for answering, but I meant that your article said that $k^0=\frac{(2\times{k^})}{m}$,but this max_num and min_num don't have self.num_hidden_layers.So I think the article maybe wrong.
![image](https://github.com/user-attachments/assets/e17cc10c-a081-4b0d-87ab-058b5123cd6e)

**Comment by Zefan-Cai** [comment]
Make sense, actually the place of m should be m-1, which is the index of k^{m-1} minus the index of k^{0}. 

Thank you so much for pointing out! We would make corresponding edition to address this.

**Comment by Couteaux123** [comment]
Thanks for answering, I understood that KV-size is k^{total}/m. Sorry for bothering you.感谢您的回答
