### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by yuhuixu1993** [Zefan-Cai/KVCache-Factory#37]
Hi, thanks for sharing this awesome project. We recently propose a new method [ThinK](https://www.arxiv.org/abs/2407.21018) which optimize the kv cache from the channel dimension. It would be very helpful to add our method as a new feature of this project. 

I would like to help working on it.

Thanks again for your OS project.

**Comment by Zefan-Cai** [comment]
Do you have an open-source implementation? We could add ThinK based on that implementation.

Also, feel free to make a PR. I am sorry that our README has not included information about how to make PR. However, you could make a PR to add ThinK into this codebase. We are open to PRs!

My email is zefncai@gmail.com. Feel free to ping me. I am more than happy to connect and help.

And I really appreciate your awesome work ThinK. I am also very excited to add ThinK implementation into this codebase.

**Comment by yuhuixu1993** [comment]
Thanks for your suggestion. I will try to submit a PR.
